<?php

return [
    'mam-non' => [
        'slug' => 'mam-non',
        'title' => 'Tiếng Anh Mầm non',
        'tag' => 'Khởi đầu',
        'short_desc' => 'Chương trình khơi gợi phản xạ nghe - nói bằng bài hát, vận động và học qua trò chơi cho trẻ nhỏ.',
        'price' => '1.250.000đ',
        'original_price' => '1.690.000đ',
        'duration' => '24 buổi',
        'level' => '4 - 6 tuổi',
        'lessons_count' => 24,
        'rating' => 4.9,
        'students' => 320,
        'image' => 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=1200&q=80',
        'instructor' => [
            'name' => 'Cô Mai Anh',
            'role' => 'Early English Specialist',
        ],
        'benefits' => [
            'Làm quen tiếng Anh tự nhiên qua vận động và tương tác.',
            'Phát âm chuẩn ngay từ giai đoạn đầu.',
            'Tăng khả năng tập trung và phản xạ ngôn ngữ.',
            'Báo cáo tiến bộ định kỳ cho phụ huynh.',
        ],
        'outline' => [
            ['title' => 'Giai đoạn 1', 'desc' => 'Làm quen âm thanh, màu sắc, con số và mẫu câu ngắn.'],
            ['title' => 'Giai đoạn 2', 'desc' => 'Học qua trò chơi, truyện tranh và hoạt động nhóm.'],
            ['title' => 'Giai đoạn 3', 'desc' => 'Nói theo mẫu, nhận diện từ vựng, tăng phản xạ.'],
            ['title' => 'Giai đoạn 4', 'desc' => 'Tổng kết bằng dự án nhỏ và bài tập về nhà có hướng dẫn.'],
        ],
        'suitable_for' => ['Trẻ mới bắt đầu', 'Phụ huynh muốn con làm quen tiếng Anh sớm', 'Học sinh cần môi trường học vui - an toàn'],
        'outcomes' => ['Nghe hiểu lệnh cơ bản', 'Phát âm từ vựng nền tảng', 'Tự tin giao tiếp ngắn'],
    ],
    'tieu-hoc' => [
        'slug' => 'tieu-hoc',
        'title' => 'Tiếng Anh Tiểu học',
        'tag' => 'Phổ biến',
        'short_desc' => 'Xây nền ngữ pháp, từ vựng và kỹ năng học tập tiếng Anh bền vững cho học sinh tiểu học.',
        'price' => '1.490.000đ',
        'original_price' => '1.990.000đ',
        'duration' => '32 buổi',
        'level' => '7 - 11 tuổi',
        'lessons_count' => 32,
        'rating' => 4.8,
        'students' => 510,
        'image' => 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=1200&q=80',
        'instructor' => [
            'name' => 'Thầy Quang Huy',
            'role' => 'Primary English Teacher',
        ],
        'benefits' => [
            'Củng cố phát âm, từ vựng và mẫu câu trọng tâm.',
            'Rèn kỹ năng đọc hiểu và viết câu đơn giản.',
            'Theo dõi tiến độ bằng bài kiểm tra ngắn mỗi giai đoạn.',
            'Phù hợp lộ trình trường lớp và nâng điểm học tập.',
        ],
        'outline' => [
            ['title' => 'Nền tảng', 'desc' => 'Từ vựng chủ đề, ngữ âm và câu cơ bản.'],
            ['title' => 'Phát triển', 'desc' => 'Đọc hiểu ngắn, viết câu và giao tiếp lớp học.'],
            ['title' => 'Luyện tập', 'desc' => 'Bài tập tổng hợp, mini project và quiz định kỳ.'],
            ['title' => 'Củng cố', 'desc' => 'Ôn tập, tăng phản xạ và chuẩn bị cấp độ cao hơn.'],
        ],
        'suitable_for' => ['Học sinh tiểu học cần tăng điểm', 'Học sinh muốn học đều 4 kỹ năng', 'Phụ huynh muốn con có lộ trình rõ ràng'],
        'outcomes' => ['Tự tin nói trong lớp', 'Đọc hiểu đoạn ngắn', 'Viết câu đúng cấu trúc'],
    ],
    'giao-tiep-phan-xa' => [
        'slug' => 'giao-tiep-phan-xa',
        'title' => 'Giao tiếp phản xạ',
        'tag' => 'Mới',
        'short_desc' => 'Tập trung nghe - nói thực chiến để tăng tốc phản xạ, ứng dụng ngay trong học tập và đời sống.',
        'price' => '1.990.000đ',
        'original_price' => '2.490.000đ',
        'duration' => '36 buổi',
        'level' => 'Thiếu niên',
        'lessons_count' => 36,
        'rating' => 4.9,
        'students' => 470,
        'image' => 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80',
        'instructor' => [
            'name' => 'Coach Linh Trang',
            'role' => 'Communication Trainer',
        ],
        'benefits' => [
            'Tăng tốc phản xạ nghe hiểu và trả lời nhanh.',
            'Luyện tình huống giao tiếp thực tế mỗi buổi.',
            'Giảm phụ thuộc vào dịch từng từ.',
            'Tăng tự tin khi nói trước đám đông.',
        ],
        'outline' => [
            ['title' => 'Input chuẩn', 'desc' => 'Nghe mẫu câu, phát âm và nhịp điệu tự nhiên.'],
            ['title' => 'Drill phản xạ', 'desc' => 'Hỏi - đáp nhanh với tình huống ngắn.'],
            ['title' => 'Role-play', 'desc' => 'Mô phỏng hội thoại theo chủ đề học viên quan tâm.'],
            ['title' => 'Thực chiến', 'desc' => 'Thuyết trình ngắn và feedback cá nhân hóa.'],
        ],
        'suitable_for' => ['Học viên muốn nói nhanh hơn', 'Người học mất gốc giao tiếp', 'Học sinh cần tự tin trước lớp'],
        'outcomes' => ['Phản xạ nhanh hơn', 'Nói rõ ý hơn', 'Giảm tâm lý sợ giao tiếp'],
    ],
    'ielts-foundation' => [
        'slug' => 'ielts-foundation',
        'title' => 'IELTS Foundation',
        'tag' => 'Nền tảng',
        'short_desc' => 'Khóa nền cho học viên chuẩn bị IELTS từ mức 3.5 đến 4.5 với trọng tâm từ vựng và ngữ pháp.',
        'price' => '2.390.000đ',
        'original_price' => '2.990.000đ',
        'duration' => '40 buổi',
        'level' => 'Band 3.5 - 4.5',
        'lessons_count' => 40,
        'rating' => 4.8,
        'students' => 390,
        'image' => 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1200&q=80',
        'instructor' => [
            'name' => 'Ms. Hạnh Vy',
            'role' => 'IELTS Foundation Coach',
        ],
        'benefits' => [
            'Nắm chắc từ vựng và ngữ pháp cốt lõi.',
            'Làm quen 4 kỹ năng theo cấu trúc IELTS.',
            'Biết cách tự học và ghi nhớ hiệu quả hơn.',
            'Có lộ trình lên band rõ ràng.',
        ],
        'outline' => [
            ['title' => 'Foundation', 'desc' => 'Xây nền từ vựng, grammar và phát âm.'],
            ['title' => 'Task practice', 'desc' => 'Làm quen đề đơn giản cho từng kỹ năng.'],
            ['title' => 'Mini test', 'desc' => 'Kiểm tra ngắn để đo mức độ tiến bộ.'],
            ['title' => 'Band path', 'desc' => 'Điều chỉnh lộ trình lên band tiếp theo.'],
        ],
        'suitable_for' => ['Người chuẩn bị vào IELTS', 'Học viên cần xây lại nền', 'Học viên mới bắt đầu'],
        'outcomes' => ['Vững nền tiếng Anh học thuật', 'Hiểu format IELTS', 'Sẵn sàng lên band tiếp theo'],
    ],
    'ielts-intensive' => [
        'slug' => 'ielts-intensive',
        'title' => 'IELTS Intensive',
        'tag' => 'Hot',
        'short_desc' => 'Tăng tốc luyện đề và chiến lược làm bài cho mục tiêu 5.5 - 6.5 trong thời gian tối ưu.',
        'price' => '3.490.000đ',
        'original_price' => '4.290.000đ',
        'duration' => '48 buổi',
        'level' => 'Band 5.5 - 6.5',
        'lessons_count' => 48,
        'rating' => 4.9,
        'students' => 280,
        'image' => 'https://images.unsplash.com/photo-1513258496099-48168024aec0?auto=format&fit=crop&w=1200&q=80',
        'instructor' => [
            'name' => 'Mr. Đức Minh',
            'role' => 'IELTS Strategy Trainer',
        ],
        'benefits' => [
            'Luyện đề theo band mục tiêu.',
            'Tối ưu chiến thuật làm bài và quản lý thời gian.',
            'Chữa bài chi tiết theo từng tiêu chí chấm.',
            'Bám sát mục tiêu đầu ra của từng học viên.',
        ],
        'outline' => [
            ['title' => 'Strategy', 'desc' => 'Xây chiến lược từng kỹ năng theo band mục tiêu.'],
            ['title' => 'Practice', 'desc' => 'Luyện đề và chữa lỗi theo rubric.'],
            ['title' => 'Speed-up', 'desc' => 'Tăng tốc làm bài, giảm lỗi thường gặp.'],
            ['title' => 'Mock test', 'desc' => 'Thi thử định kỳ với phản hồi cá nhân hóa.'],
        ],
        'suitable_for' => ['Học viên cần tăng band nhanh', 'Người đã có nền nhưng thiếu chiến thuật', 'Người cần luyện đề nhiều'],
        'outcomes' => ['Điểm số ổn định hơn', 'Viết và nói mạch lạc hơn', 'Làm bài đúng chiến thuật'],
    ],
    'ielts-advance' => [
        'slug' => 'ielts-advance',
        'title' => 'IELTS Advance',
        'tag' => 'Tăng tốc',
        'short_desc' => 'Chương trình nâng band 6.5+ với chiến lược, phân tích lỗi sâu và cá nhân hóa theo mục tiêu cao.',
        'price' => '4.490.000đ',
        'original_price' => '5.490.000đ',
        'duration' => '56 buổi',
        'level' => 'Band 6.5+',
        'lessons_count' => 56,
        'rating' => 5.0,
        'students' => 160,
        'image' => 'https://images.unsplash.com/photo-1543269865-cbf427effbad?auto=format&fit=crop&w=1200&q=80',
        'instructor' => [
            'name' => 'Ms. Ngọc Hân',
            'role' => 'Advanced IELTS Mentor',
        ],
        'benefits' => [
            'Phân tích lỗi sâu theo từng band descriptor.',
            'Luyện kỹ năng viết và nói nâng cao.',
            'Tối ưu cách triển khai ý và lập luận.',
            'Có kế hoạch tăng band theo giai đoạn.',
        ],
        'outline' => [
            ['title' => 'Gap analysis', 'desc' => 'Xác định lỗ hổng và ưu tiên sửa lỗi.'],
            ['title' => 'Deep practice', 'desc' => 'Luyện chuyên sâu từng kỹ năng khó.'],
            ['title' => 'Feedback loop', 'desc' => 'Nhận góp ý chi tiết sau mỗi buổi học.'],
            ['title' => 'Final sprint', 'desc' => 'Nâng band bằng bài test mục tiêu.'],
        ],
        'suitable_for' => ['Học viên muốn 6.5+', 'Người cần nâng band gấp', 'Học viên đã có nền khá'],
        'outcomes' => ['Band cao hơn', 'Bài viết rõ ràng hơn', 'Phát triển tư duy học thuật'],
    ],
    'tieng-anh-he' => [
        'slug' => 'tieng-anh-he',
        'title' => 'Tiếng Anh Hè',
        'tag' => 'Mùa hè',
        'short_desc' => 'Lớp học mùa hè cân bằng giữa kiến thức, hoạt động nhóm và trải nghiệm tiếng Anh vui nhộn.',
        'price' => '2.100.000đ',
        'original_price' => '2.690.000đ',
        'duration' => '8 tuần',
        'level' => 'Theo độ tuổi',
        'lessons_count' => 16,
        'rating' => 4.7,
        'students' => 240,
        'image' => 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=1200&q=80',
        'instructor' => [
            'name' => 'Cô Thu Hà',
            'role' => 'Summer Camp Lead',
        ],
        'benefits' => [
            'Học nhẹ nhàng nhưng vẫn giữ nhịp tiếng Anh.',
            'Hoạt động sáng tạo, phù hợp kỳ nghỉ hè.',
            'Tăng giao tiếp qua trò chơi và dự án nhỏ.',
            'Giữ hứng thú học tập suốt mùa hè.',
        ],
        'outline' => [
            ['title' => 'Warm-up', 'desc' => 'Khởi động bằng bài hát và hoạt động nhóm.'],
            ['title' => 'Theme learning', 'desc' => 'Học theo chủ đề gần gũi với đời sống.'],
            ['title' => 'Project time', 'desc' => 'Thực hiện mini project theo nhóm.'],
            ['title' => 'Showcase', 'desc' => 'Trình bày sản phẩm và tổng kết cuối khóa.'],
        ],
        'suitable_for' => ['Học sinh nghỉ hè', 'Học viên muốn duy trì nhịp học', 'Phụ huynh cần lớp học nhẹ nhàng'],
        'outcomes' => ['Giữ thói quen học', 'Nói tiếng Anh tự nhiên hơn', 'Tăng tương tác nhóm'],
    ],
    'tieng-anh-doanh-nghiep' => [
        'slug' => 'tieng-anh-doanh-nghiep',
        'title' => 'Tiếng Anh Doanh nghiệp',
        'tag' => 'Chuyên sâu',
        'short_desc' => 'Thiết kế cho người đi làm cần sử dụng tiếng Anh trong họp, email, thuyết trình và thương lượng.',
        'price' => '2.850.000đ',
        'original_price' => '3.490.000đ',
        'duration' => '30 buổi',
        'level' => 'Người đi làm',
        'lessons_count' => 30,
        'rating' => 4.8,
        'students' => 210,
        'image' => 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80',
        'instructor' => [
            'name' => 'Mr. Tấn Phát',
            'role' => 'Business English Coach',
        ],
        'benefits' => [
            'Học đúng ngôn ngữ công việc hằng ngày.',
            'Luyện email, meeting và presentation.',
            'Tăng sự tự tin khi làm việc với khách hàng quốc tế.',
            'Cá nhân hóa theo ngành nghề và vị trí công việc.',
        ],
        'outline' => [
            ['title' => 'Business basics', 'desc' => 'Mẫu câu email, họp và giao tiếp công sở.'],
            ['title' => 'Role-play', 'desc' => 'Thực hành tình huống với đồng nghiệp và khách hàng.'],
            ['title' => 'Presenting', 'desc' => 'Luyện thuyết trình và phản hồi chuyên nghiệp.'],
            ['title' => 'Workplace fluency', 'desc' => 'Tối ưu phản xạ trong môi trường làm việc.'],
        ],
        'suitable_for' => ['Người đi làm', 'Nhân sự cần tiếng Anh công sở', 'Người chuẩn bị làm việc với đối tác quốc tế'],
        'outcomes' => ['Email rõ ràng hơn', 'Họp tự tin hơn', 'Giao tiếp công việc mạch lạc hơn'],
    ],
];