<?php
declare(strict_types=1);

return [
	'cv-it' => [
		'slug' => 'cv-it',
		'title' => 'Kỹ năng viết CV IT chuẩn Nhật Bản',
		'type' => 'Workshop',
		'date' => '25 Tháng 5, 2026',
		'time' => '08:30 - 11:30',
		'registered' => 45,
		'capacity' => 50,
		'location' => 'Phòng A-203',
		'address' => 'Tầng 2, Khu học thuật',
		'instructor' => 'Tokyo Career Lab',
		'description' => 'Cùng chuyên gia đến từ Tokyo tìm hiểu cách viết CV chinh phục nhà tuyển dụng IT Nhật Bản.',
		'longDescription' => 'Buổi workshop giúp học viên hoàn thiện hồ sơ ứng tuyển, cách trình bày kinh nghiệm và kỹ năng theo chuẩn doanh nghiệp Nhật. Nội dung tập trung vào bố cục CV, từ ngữ chuyên môn và những lỗi thường gặp khiến hồ sơ bị loại.',
		'benefits' => [
			'Hiểu cấu trúc CV chuẩn Nhật Bản',
			'Luyện sửa CV theo từng vị trí ứng tuyển',
			'Được góp ý trực tiếp từ chuyên gia',
		],
		'tagClass' => 'text-indigo-600 bg-indigo-50',
		'progressClass' => 'bg-rose-500',
		'status' => 'registered',
	],
	'speaking-club' => [
		'slug' => 'speaking-club',
		'title' => 'English Speaking Club',
		'type' => 'Câu lạc bộ',
		'date' => '02 Tháng 6, 2026',
		'time' => '17:30 - 19:00',
		'registered' => 28,
		'capacity' => 40,
		'location' => 'Sân khấu trung tâm',
		'address' => 'Khu sinh hoạt chung',
		'instructor' => 'Teacher Sarah',
		'description' => 'Thực hành phản xạ giao tiếp qua trò chơi, thảo luận nhóm và mini challenge theo chủ đề hàng tuần.',
		'longDescription' => 'Câu lạc bộ là không gian thực hành nói tiếng Anh tự nhiên, tăng phản xạ và sự tự tin trước đám đông. Học viên sẽ tham gia các hoạt động tương tác, tranh luận và đóng vai theo chủ đề.',
		'benefits' => [
			'Tăng phản xạ giao tiếp',
			'Rèn kỹ năng nói trước nhóm',
			'Thực hành qua tình huống thực tế',
		],
		'tagClass' => 'text-blue-600 bg-blue-50',
		'progressClass' => 'bg-blue-500',
		'status' => 'registered',
	],
	'ielts-mock-test-day' => [
		'slug' => 'ielts-mock-test-day',
		'title' => 'IELTS Mock Test Day',
		'type' => 'Thi thử',
		'date' => '12 Tháng 6, 2026',
		'time' => '08:00 - 12:00',
		'registered' => 60,
		'capacity' => 60,
		'location' => 'Phòng thi 01',
		'address' => 'Khu kiểm tra năng lực',
		'instructor' => 'Academic Team',
		'description' => 'Làm bài thi thử với cấu trúc gần sát đề thật, sau đó nhận phân tích chi tiết từng kỹ năng.',
		'longDescription' => 'Sự kiện mô phỏng bài thi IELTS thật với đủ 4 kỹ năng. Sau khi hoàn thành, học viên sẽ được phân tích điểm mạnh, điểm yếu và nhận lộ trình cải thiện cụ thể.',
		'benefits' => [
			'Làm quen với áp lực thời gian',
			'Đánh giá trình độ hiện tại',
			'Nhận nhận xét và lộ trình cải thiện',
		],
		'tagClass' => 'text-emerald-600 bg-emerald-50',
		'progressClass' => 'bg-emerald-500',
		'status' => 'available',
	],
	'parent-connect-day' => [
		'slug' => 'parent-connect-day',
		'title' => 'Parent Connect Day',
		'type' => 'Gặp gỡ',
		'date' => '18 Tháng 6, 2026',
		'time' => '14:00 - 16:30',
		'registered' => 32,
		'capacity' => 35,
		'location' => 'Hội trường',
		'address' => 'Tầng 1, Khu sự kiện',
		'instructor' => 'Ban điều hành',
		'description' => 'Buổi trao đổi giữa phụ huynh, học viên và giáo viên về tiến độ học tập, mục tiêu và lộ trình sắp tới.',
		'longDescription' => 'Sự kiện kết nối phụ huynh với nhà trường để cập nhật tình hình học tập, trao đổi kỳ vọng và thống nhất lộ trình hỗ trợ học viên trong giai đoạn tiếp theo.',
		'benefits' => [
			'Đồng bộ mục tiêu học tập',
			'Trao đổi trực tiếp với giáo viên',
			'Nắm rõ tiến độ và kế hoạch tiếp theo',
		],
		'tagClass' => 'text-amber-600 bg-amber-50',
		'progressClass' => 'bg-amber-500',
		'status' => 'available',
	],
];
